export enum ContractType {
  CLT = "CLT",
  PJ = "PJ"
}

export enum WorkerStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  TERMINATED = "TERMINATED",
  ON_VACATION = "ON_VACATION"
}

export enum DocumentType {  
  RG = "RG",
  CPF = "CPF",
  CNH = "CNH", 
  PASSPORT = "PASSPORT",
  WORK_CONTRACT = "WORK_CONTRACT",
  WORKER_CONTRACT = "WORKER_CONTRACT", 
  SERVICE_CONTRACT = "SERVICE_CONTRACT", 
  NDA = "NDA", 
  INVOICE = "INVOICE", 
  RECEIPT = "RECEIPT", 
  REPORT = "REPORT", 
  MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE",
  ADMISSION_DOCUMENT = "ADMISSION_DOCUMENT",
  DISMISSAL_DOCUMENT = "DISMISSAL_DOCUMENT",
  CERTIFICATE = "CERTIFICATE",
  PROPOSAL = "PROPOSAL", 
  MEMO = "MEMO", 
  LETTER = "LETTER", 
  FORM = "FORM", 
  POLICY = "POLICY", 
  PRESENTATION = "PRESENTATION", 
  OTHER = "OTHER"
}

export enum InvoiceStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  OVERDUE = "OVERDUE"
}

export enum VisitorStatus {
  EXPECTED = 'EXPECTED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  CANCELLED = 'CANCELLED'
}

export enum ProviderStatus {
  EXPECTED = 'EXPECTED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  CANCELLED = 'CANCELLED'
}